name: eShop build

on: 
  push:
    paths: 
      - 'src/Services/Coupon/**'
      - 'test/ServicesCoupon/**'
    branches: [main]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from the repository
        uses: actions/checkout@v1
        with:
          ref: main
      - name: Run unit tests
        run: dotnet test tests/Services/Coupon/*.Tests/*.csproj
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          DOTNET_LOGO: false
      - name: build and push Docker-image
        uses: docker/build-push-action@vq
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          paswword: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER}}
          path: .
          dockerfile: './src/Services/Coupon/Coupon.API/Dockerfile.acr'
          repositury: 'coupon.api'  
          tags: 'linux-latest'
          push: true
